
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 7
 
influxdb:
  host: localhost
  port: 8086
  database: db_ha
  username: root
  password: root
  ssl: false
  verify_ssl: true
  max_retries: 3
  measurement_attr: entity_id
#  default_measurement: state
#  exclude:
#    entities:
#       - sun.sun
#    domains:
#       - sun
  include:
    entities:   
       - binary_sensor.lumi_lumi_sensor_magnet_aq2_81e3a102_on_off
       - sensor.lumi_lumi_weather_831f4b05_temperature
       - sensor.lumi_lumi_weather_831f4b05_humidity
       - sensor.lumi_lumi_weather_831f4b05_pressure
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature
    sensor.*pressure:
      override_measurement: pressure
    binary_sensor.*_on_off:
      override_measurement: on_off
  tags:
    instance: prod
    source: hass
